version: '3.7'

services:
  web:
    build: .
    image: autodesk_forge
    container_name: web
    command: /start
    networks:
      - frontend
      - backend
    expose:
      - 5000
    volumes:
      - .:/app
    env_file:
      - ./.env
    restart: always

  nginx:
    build: ./nginx
    image: reverse_proxy_nginx
    container_name: nginx
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - frontend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O /dev/null http://localhost || exit 1"
        ]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  frontend:
    name: custom_frontend
    driver: bridge
  backend:
    name: custom_backend
    driver: bridge
